Add Molecule job for copy-containers
openstack-k8s-operators/ci-framework pull request #1002
Opened 2024-01-05 07:03 UTC by raukadah

It will help to test the copy-container golang binary build process.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/999

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [ ] Appropriate documentation exists and/or is up-to-date:
  - [ ] README in the role
  - [ ] Content of the docs/source is reflecting the changes

2024-01-05 10:15 UTC, raukadah commented on roles/copy_container/molecule/default/converge.yml
> +        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/roles/copy_container/files/copy-quay"
Hi @arxcruz We are trying to add molecule job to test copy_container role.
At this step in the molecule job, we are hitting [following issue ](https://logserver.rdoproject.org/02/1002/ea75b0c27af90efd6604c3f6c6b7fec5ac234298/github-check/cifmw-molecule-copy_container/0384143/job-output.txt)while passing release as antelope or master
```
 TASK [Copy containers from RDO quay to local registry] *************************
2024-01-05 05:11:04.144870 | controller | fatal: [instance]: FAILED! => changed=true
2024-01-05 05:11:04.144952 | controller |   cmd:
2024-01-05 05:11:04.144961 | controller |   - copy-quay
2024-01-05 05:11:04.144976 | controller |   - --debug
2024-01-05 05:11:04.144983 | controller |   - --pull-registry
2024-01-05 05:11:04.145443 | controller |   - quay.rdoproject.org
2024-01-05 05:11:04.145490 | controller |   - --from-namespace
2024-01-05 05:11:04.145502 | controller |   - podified-antelope-centos9
2024-01-05 05:11:04.145522 | controller |   - --push-registry
2024-01-05 05:11:04.145536 | controller |   - 127.0.0.1:5001
2024-01-05 05:11:04.145744 | controller |   - --to-namespace
2024-01-05 05:11:04.146294 | controller |   - podified-antelope-centos9
2024-01-05 05:11:04.146358 | controller |   - --release
2024-01-05 05:11:04.146370 | controller |   - master
2024-01-05 05:11:04.146380 | controller |   - copy
2024-01-05 05:11:04.146397 | controller |   - openstack-os
2024-01-05 05:11:04.146481 | controller |   delta: '0:00:00.033781'
2024-01-05 05:11:04.146644 | controller |   end: '2024-01-05 05:11:04.103971'
2024-01-05 05:11:04.146675 | controller |   msg: non-zero return code
2024-01-05 05:11:04.147069 | controller |   rc: 1
2024-01-05 05:11:04.147096 | controller |   start: '2024-01-05 05:11:04.070190'
2024-01-05 05:11:04.147107 | controller |   stderr: time="2024-01-05T05:11:04-05:00" level=fatal msg="no entry found for release master"
2024-01-05 05:11:04.147646 | controller |   stderr_lines: <omitted>
2024-01-05 05:11:04.147670 | controller |   stdout: ''
2024-01-05 05:11:04.147681 | controller |   stdout_lines: <omitted>
```
Please have a look, thank you :-)

2024-01-05 11:30 UTC, arxcruz approved these changes
lgtm

2024-01-07 23:42 UTC, lewisdenny commented
recheck

2024-01-08 02:26 UTC, lewisdenny commented
@raukadah @arxcruz An entry needs to be added into the config file [1] as were failing here [2]

[1] https://github.com/openstack-k8s-operators/ci-framework/blob/be22d6787a3db72a8b1d691a059b990c7781e4ca/roles/copy_container/files/copy-quay/config.yaml#L5
[2] https://github.com/openstack-k8s-operators/ci-framework/blob/be22d6787a3db72a8b1d691a059b990c7781e4ca/roles/copy_container/files/copy-quay/main.go#L86

2024-01-08 02:28 UTC, lewisdenny requested changes
@raukadah @arxcruz An entry needs to be added into the config file [1] as were failing here [2]

[1] https://github.com/openstack-k8s-operators/ci-framework/blob/be22d6787a3db72a8b1d691a059b990c7781e4ca/roles/copy_container/files/copy-quay/config.yaml#L5-L18
[2] https://github.com/openstack-k8s-operators/ci-framework/blob/be22d6787a3db72a8b1d691a059b990c7781e4ca/roles/copy_container/files/copy-quay/main.go#L86-100

2024-01-08 08:37 UTC, pablintino commented
@raukadah thanks for taking this point I mentioned the past day day during the sync

2024-01-11 08:03 UTC, raukadah commented
> @raukadah @arxcruz An entry needs to be added into the config file [1] as were failing here [2]
> 
> [1] https://github.com/openstack-k8s-operators/ci-framework/blob/be22d6787a3db72a8b1d691a059b990c7781e4ca/roles/copy_container/files/copy-quay/config.yaml#L5-L18 [2] https://github.com/openstack-k8s-operators/ci-framework/blob/be22d6787a3db72a8b1d691a059b990c7781e4ca/roles/copy_container/files/copy-quay/main.go#L86-100

Done

2024-01-11 09:24 UTC, cjeanner reviewed
/approve

thanks for adding this new test, hopefully it will ensure we don't blow things when we update go dependencies :)

2024-01-11 10:07 UTC, arxcruz approved these changes
lgtm

2024-01-11 10:22 UTC, merged