WIP: Change nodesets to use unified labels
openstack-k8s-operators/ci-framework pull request #1024
Opened 2024-01-15 21:57 UTC by rlandy

This PRs removes Vexxhost-specific node labels
to use unified node labels that can take advantage of other cloud providers.

Note that this is still WIP as not all the unified labels exist yet. Waiting on a patch from
software factory for the missing labels.

As a pull request owner and reviewers, I checked that:
- [x ] Appropriate testing is done and actually running
- [x ] Appropriate documentation exists and/or is up-to-date:
  - [x ] README in the role
  - [x ] Content of the docs/source is reflecting the changes

2024-02-07 03:13 UTC, lewisdenny requested changes
Hey @rlandy we are getting `NODE_FAILURE Node request` errors on at least `cloud-centos-9-stream-tripleo` label

2024-02-07 10:58 UTC, lewisdenny commented
recheck

2024-02-07 11:43 UTC, morucci commented
recheck

2024-02-07 12:16 UTC, morucci commented
recheck

2024-02-07 13:26 UTC, morucci commented
recheck

2024-02-07 15:02 UTC, nhicher commented
recheck

2024-02-08 10:17 UTC, lewisdenny commented
recheck

podified-multinode-hci-deployment-crc failing on `unable to default to a user name: the server is currently unable to handle the request` which is unrelated to this PR

2024-02-08 12:11 UTC, lewisdenny commented
recheck

2024-02-08 14:05 UTC, closed without merging