Update cifmw-adoption-base to CRC 2.30 (OCP 4.14)
openstack-k8s-operators/ci-framework pull request #1113
Opened 2024-02-07 00:00 UTC by lewisdenny

- Update from crc 2.19 to 2.30
- Extract nodeset from inline to nodeset.yaml

JIRA: OSPRH-4340
JIRA: OSPRH-2712

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running

2024-02-07 03:15 UTC, lewisdenny commented on zuul.d/nodeset.yaml
> +        label: cloud-centos-9-stream-tripleo
Dropping the vexxhost as per https://github.com/openstack-k8s-operators/ci-framework/pull/1024

2024-02-07 05:47 UTC, lewisdenny commented
recheck

2024-02-07 07:23 UTC, marios reviewed
looks right. holding the approve though until we're ready for merge (ping me if you need an approve set)

2024-02-07 07:26 UTC, marios requested changes
just noticed we have NODE_FAILURE for the zuul run 

https://review.rdoproject.org/zuul/buildset/be052482be5d441a9c1beb80c47f35c7

there are no logs there but it seems consistent in this pull request i mean has there been any green run here?

2024-02-07 10:25 UTC, lewisdenny commented
Same failure on https://github.com/openstack-k8s-operators/ci-framework/pull/1024#issuecomment-1930835802 so I think it's an issue with the label even though we see it at [1]

Updating to the old label now

[1] https://softwarefactory-project.io/zuul/t/rdoproject.org/labels

2024-02-07 11:30 UTC, morucci commented
recheck

2024-02-08 07:08 UTC, marios approved these changes
thanks for update looks good now

the current proposal is a straight copy of the inline nodeset to a named definition (*except the label for crc to use 2.30 obv)

2024-02-08 10:28 UTC, cjeanner commented on zuul.d/nodeset.yaml
> +      - name: computes
while at it, we may want to add an "ocps" group, containing the "crc" node. That would help converging I think.

2024-02-08 11:26 UTC, cjeanner commented
/approve

2024-02-08 14:10 UTC, cescgina reviewed
/lgtm

2024-02-08 15:46 UTC, cescgina commented
recheck

2024-02-08 18:21 UTC, merged