Return DLRN MD5 hash to the child job
openstack-k8s-operators/ci-framework pull request #1158
Opened 2024-02-16 13:04 UTC by raukadah

Due to multiple promotions, the tcib job and child job gets different current-podified hashes leading failure of pulling containers in the EDPM deployment jobs.

Returning the dlrn md5 hash to the child job makes sure we populate the same repo on the node.

Note: It also set the returned dlrn md5 hash to the repo-setup to generate proper repos with passed dlrn hash.

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [ ] Appropriate documentation exists and/or is up-to-date:
  - [ ] README in the role
  - [ ] Content of the docs/source is reflecting the changes

2024-02-16 13:06 UTC, cjeanner commented on ci/playbooks/tcib/run.yml
wondering if we wouldn't need something like that for the "content provider reproducer" ? Otherwise, sounds legit.

2024-02-16 14:57 UTC, hjensas approved these changes
This fixed the issue I had with missmatching hash'es on https://gitlab.cee.redhat.com/ci-framework/ci-framework-testproject/-/merge_requests/36.

2024-02-16 16:25 UTC, raukadah commented
recheck

2024-02-16 17:01 UTC, cjeanner commented
/approve

2024-02-19 01:34 UTC, lewisdenny commented
recheck

2024-02-19 04:00 UTC, lewisdenny requested changes
Only had a quick look but:

Writing the file works fine[1], it's collected [2] but not found?

Seems everything is running on the same node(controller) so not sure what's happening here.
```
2024-02-16 11:29:39.207860 | controller | TASK [repo_setup : Dump full hash in delorean.repo.md5 file content={{ _repo_setup_json['full_hash'] }}
2024-02-16 11:29:39.207866 | controller | , dest={{ cifmw_repo_setup_basedir }}/artifacts/repositories/delorean.repo.md5] ***
2024-02-16 11:29:39.207872 | controller | Friday 16 February 2024  11:29:39 -0500 (0:00:00.774)       0:00:10.993 *******
2024-02-16 11:29:39.729169 | controller | changed: [localhost]
```

[2] https://logserver.rdoproject.org/58/1158/3cb71c1758ed139e62fea7ca85b26512028ef11a/github-check/cifmw-tcib/d4778ee/ci-framework-data/artifacts/repositories/delorean.repo.md5

[3] 
```
2024-02-16 17:14:05.053769 | TASK [Slurp dlrn md5 hash]
2024-02-16 17:14:05.316330 | controller | ERROR
2024-02-16 17:14:05.316506 | controller | {
2024-02-16 17:14:05.316536 | controller |   "msg": "file not found:  /home/zuul/ci-framework-data/artifacts/repositories/delorean.repo.md5"
2024-02-16 17:14:05.316558 | controller | }
```

2024-02-19 05:46 UTC, raukadah commented
> Only had a quick look but:
> 
> Writing the file works fine[1], it's collected [2] but not found?
> 
> Seems everything is running on the same node(controller) so not sure what's happening here.
> 
> ```
> 2024-02-16 11:29:39.207860 | controller | TASK [repo_setup : Dump full hash in delorean.repo.md5 file content={{ _repo_setup_json['full_hash'] }}
> 2024-02-16 11:29:39.207866 | controller | , dest={{ cifmw_repo_setup_basedir }}/artifacts/repositories/delorean.repo.md5] ***
> 2024-02-16 11:29:39.207872 | controller | Friday 16 February 2024  11:29:39 -0500 (0:00:00.774)       0:00:10.993 *******
> 2024-02-16 11:29:39.729169 | controller | changed: [localhost]
> ```
> 
> [2] https://logserver.rdoproject.org/58/1158/3cb71c1758ed139e62fea7ca85b26512028ef11a/github-check/cifmw-tcib/d4778ee/ci-framework-data/artifacts/repositories/delorean.repo.md5
> 
> [3]
> 
> ```
> 2024-02-16 17:14:05.053769 | TASK [Slurp dlrn md5 hash]
> 2024-02-16 17:14:05.316330 | controller | ERROR
> 2024-02-16 17:14:05.316506 | controller | {
> 2024-02-16 17:14:05.316536 | controller |   "msg": "file not found:  /home/zuul/ci-framework-data/artifacts/repositories/delorean.repo.md5"
> 2024-02-16 17:14:05.316558 | controller | }
> ```

Thank you @lewisdenny for taking a look at the pr. Yes, it's wired. I have added a task to check for that file. It will give some more data.

2024-02-19 13:08 UTC, raukadah commented
recheck dpa job failure unrelated

2024-02-19 15:48 UTC, cjeanner commented on roles/repo_setup/tasks/configure.yml
> +  when: content_provider_dlrn_md5_hash is defined
I have the feeling this will be defined to "nowhere" - is this really what we want?

2024-02-19 15:54 UTC, cjeanner commented
/override rdoproject.org/github-check

The failure isn't related to that change.

2024-02-19 16:16 UTC, merged