Configure vnet devices with the required vlan ids.
openstack-k8s-operators/ci-framework pull request #1299
Opened 2024-03-20 11:40 UTC by psathyan

When the libvirt network is created outside of dev-scripts purview, then we need to ensure the proper VLAN tagging of the vnet interfaces. If the interfaces are not configured then the communication in the tagged networks is broken.

This change set ensures when apply the gathered VLAN ids from the given networks and configured those interfaces attached to it.

A new `module` name `bridge_vlan` is introduced to support this functionality.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] Content of the docs/source is reflecting the changes

Closes: OSPRH-5656

2024-04-01 12:20 UTC, pablintino requested changes

2024-04-01 12:20 UTC, pablintino commented on plugins/modules/bridge_vlan.py
> +                _result["networks"][_net] = deepcopy(net_info)
I don't think this is OK. What happens if the the loop runs twice with the first iteration failing and the second one passing? The second iteration will set the success to True and failed to False, leading to an unexpected result.

2024-04-01 12:20 UTC, pablintino commented on plugins/modules/bridge_vlan.py
> +                _result["networks"][_net] = dict(
This is not flagging the result as failed, but I think it should do so.

2024-04-02 07:07 UTC, psathyan reviewed
@pablintino thanks for taking the time to review and provide feedback.

2024-04-02 07:08 UTC, psathyan commented on roles/reproducer/tasks/main.yml
> +  bridge_vlan:
Let me fix it in the latest commit.

2024-04-02 07:08 UTC, psathyan commented on roles/devscripts/tasks/300_post.yml
> +      bridge_vlan:
Let me fix it in the latest commit.

2024-04-02 09:43 UTC, pablintino commented
/approve

2024-04-03 09:02 UTC, pablintino commented
/lgtm

2024-04-03 09:33 UTC, merged