Donot generate nova migration key if exists
openstack-k8s-operators/ci-framework pull request #1311
Opened 2024-03-21 08:52 UTC by raukadah

If we re-run the deploy-architecture.sh script. Then Create nova migration keypair task fails with error:
```
Unable to read the key. The key is protected with a passphrase or broken.
```

In order to fix this issue, we donot need to regenerate the key but to reuse it.

This pr checks for nova migration key if exists. Reuse the same.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

2024-03-21 10:14 UTC, lewisdenny requested changes

2024-03-21 10:14 UTC, lewisdenny commented on playbooks/06-deploy-architecture.yml
> +        path: "{{ cifmw_basedir }}/artifacts/nova_migration_key"
I would either update line 41 to match line 33 or vice-versa

2024-03-21 15:49 UTC, cjeanner commented on playbooks/06-deploy-architecture.yml
> +          filename: "{{ _nova_key_file.stat.path }}"
you want to use the same "{{ _nova_key_file.stat.path }}" on line 47 so that we avoid repetition (I think this is what @lewisdenny said)

2024-03-22 03:57 UTC, lewisdenny approved these changes
/lgtm

Thanks Chandan!

2024-03-22 05:35 UTC, lewisdenny commented
/lgtm

2024-03-22 09:28 UTC, cjeanner commented
/approve
/lgtm

2024-03-22 09:29 UTC, cjeanner commented
/lgtm

I'm too fast...

2024-03-22 14:36 UTC, cjeanner commented
/lgtm

2024-03-23 13:08 UTC, raukadah commented
recheck

2024-03-23 14:45 UTC, merged