Refine a bit validate-architecture related make targets
openstack-k8s-operators/ci-framework pull request #1727
Opened 2024-05-17 13:01 UTC by cjeanner

This patch refines a bit the targets involved in the
"architecture_test". It now creates a new volume to store your generated
snippets, allowing to review them once the container is removed.
It also allows to pass any arbitrary `ansible-playbook` options down to
the test run, so that you can point to additional environment files,
pass extra parameters and so on.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

2024-05-21 04:22 UTC, lewisdenny requested changes

2024-05-21 06:15 UTC, cjeanner commented on Makefile
>  .PHONY: run_ctx_architecture_test
I'd rather avoid defaults there, since they heavily depend on the user environment.

Updated doc, referring the container one for the "full doc".

2024-05-21 06:16 UTC, cjeanner commented on Makefile
>  .PHONY: architecture_test_nodeps
should do the trick.

2024-05-21 12:22 UTC, lewisdenny commented
@cjeanner Thanks mate, lgtm now, just need some `trim` in your life

2024-05-22 08:38 UTC, lewisdenny approved these changes
/lgtm

2024-05-22 09:31 UTC, raukadah commented
/approve

2024-05-22 09:41 UTC, merged