Add support to run IT tests in MacOS and arm64
openstack-k8s-operators/ci-framework pull request #1805
Opened 2024-05-31 14:16 UTC by pablintino

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

2024-06-02 23:17 UTC, lewisdenny commented on tests/integration/targets/kustomize/tasks/main.yml
> +        src: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.1.1/kustomize_v5.4.2_{{ _os_string }}_{{ _arch_string }}.tar.gz
```suggestion
        src: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_{{ _os_string }}_{{ _arch_string }}.tar.gz
```

2024-06-02 23:25 UTC, lewisdenny requested changes
Thanks Pablo, along with https://github.com/openstack-k8s-operators/ci-framework/pull/1807 this allows running tests locally on ARM Mac with the small nit I suggested.

2024-06-03 09:01 UTC, rebtoor approved these changes

2024-06-03 09:01 UTC, rebtoor commented
/approve

2024-06-03 12:56 UTC, merged