Ensure virtqemud-sock is present before cleaning
openstack-k8s-operators/ci-framework pull request #1904
Opened 2024-06-19 06:16 UTC by cjeanner

While the usual usage is "deploy, then clean", jobs in CI might start
with a "clean, then deploy".

In such case, it might happen all of the dependencies are installed
during the node bootstrap, but libvirt services aren't switched to the
modular daemons layout, leading to a crash with the current
implementation.

This patch adds a sanity check on the virtqemud-sock file availability,
to ensure everything's fine.

Molecule job has also been modified to "clean" before "deploy" so that
we should hopefully catch issues earlier.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

2024-06-19 07:13 UTC, pablintino commented
/approve

2024-06-19 08:01 UTC, rebtoor approved these changes

2024-06-19 08:08 UTC, rebtoor requested changes

2024-06-19 08:08 UTC, rebtoor commented on roles/libvirt_manager/molecule/deploy_layout/prepare.yml
> +        tasks_from: cleanup_layout.yml
```suggestion
      ansible.builtin.import_role:
        name: libvirt_manager
        tasks_from: clean_layout.yml
```

2024-06-19 10:41 UTC, rebtoor approved these changes

2024-06-19 17:08 UTC, cjeanner commented
recheck

2024-06-20 09:38 UTC, rebtoor approved these changes

2024-06-20 12:53 UTC, cjeanner commented
recheck

2024-06-20 17:24 UTC, merged