Dropping dataplane-operator references
openstack-k8s-operators/ci-framework pull request #1907
Opened 2024-06-19 10:02 UTC by fao89

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

2024-06-19 10:10 UTC, rebtoor requested changes

2024-06-19 10:10 UTC, rebtoor commented on roles/edpm_deploy_baremetal/tasks/main.yml
> +          } if ('openstack-operator' in operators_build_output)
probably we just need to get rid of the combine since we have OPENSTACK_REPO and OPENSTACK_BRANCH already defined.

2024-06-19 13:38 UTC, fao89 commented
recheck

2024-06-19 18:51 UTC, fao89 commented
recheck

2024-06-20 10:09 UTC, fao89 commented
recheck

2024-06-20 13:19 UTC, fao89 commented
it keeps failing on keystone
```
--- FAIL: kuttl (611.03s)
        --- FAIL: kuttl/harness (0.00s)
            --- FAIL: kuttl/harness/change_keystone_config (180.59s)
            --- FAIL: kuttl/harness/keystone_scale (181.03s)
            --- PASS: kuttl/harness/keystone_tls (68.29s)
            --- FAIL: kuttl/harness/keystone_resources (181.08s)
```

2024-06-20 18:13 UTC, fao89 commented
recheck

2024-06-25 11:33 UTC, fao89 commented
@rebtoor @viroel could you please take a look?

2024-08-02 11:14 UTC, pablintino commented
/approve

2024-08-03 22:23 UTC, rebtoor approved these changes
/lgtm

2024-08-03 22:38 UTC, merged