Add support for live documentation editing
openstack-k8s-operators/ci-framework pull request #2001
Opened 2024-07-02 02:33 UTC by lewisdenny

This patch adds the docs-live make target. This make target uses
`sphinx-autobuild` to rebuild and reload docuemtnation content in the
browser.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

2024-07-02 08:28 UTC, jpodivin requested changes
The plugins, roles and utils are not getting build for live version. 
```
/home/jpodivin/repos/ci-framework/docs/source/index.rst:95: WARNING: toctree glob pattern 'plugins/*' didn't match any documents
/home/jpodivin/repos/ci-framework/docs/source/index.rst:102: WARNING: toctree glob pattern 'module_utils/*' didn't match any documents
/home/jpodivin/repos/ci-framework/docs/source/index.rst:109: WARNING: toctree glob pattern 'roles/*' didn't match any documents

You can work around it by building the standard version first, and using the `sphinx-autobuild` just to serve it. But I'm not sure if the changes are going to propagate that way.

2024-07-02 08:28 UTC, jpodivin commented on Makefile
> +.PHONY: docs-live
nit: the convention in this makefile is to use underscores `_` rather than dashes `-`.

2024-07-03 02:22 UTC, lewisdenny commented
> The plugins, roles and utils are not getting build for live version.
> 
> ```
> /home/jpodivin/repos/ci-framework/docs/source/index.rst:95: WARNING: toctree glob pattern 'plugins/*' didn't match any documents
> /home/jpodivin/repos/ci-framework/docs/source/index.rst:102: WARNING: toctree glob pattern 'module_utils/*' didn't match any documents
> /home/jpodivin/repos/ci-framework/docs/source/index.rst:109: WARNING: toctree glob pattern 'roles/*' didn't match any documents
> 
> You can work around it by building the standard version first, and using the `sphinx-autobuild` just to serve it. But I'm not sure if the changes are going to propagate that way. 
> ```

Thanks @jpodivin , I have added a new docs make target to build the auto generated content. I then pass that to `sphinx-autobuild as a `--pre-build` command. I also added the source plugins directory as one to watch for changes and excluded the generated content from the watch as it causes a loop. 

Please test and let me know if that helps the issues you discovered!

2024-07-03 11:25 UTC, jpodivin approved these changes

2024-07-03 11:26 UTC, jpodivin commented
> > The plugins, roles and utils are not getting build for live version.
> > ```
> > /home/jpodivin/repos/ci-framework/docs/source/index.rst:95: WARNING: toctree glob pattern 'plugins/*' didn't match any documents
> > /home/jpodivin/repos/ci-framework/docs/source/index.rst:102: WARNING: toctree glob pattern 'module_utils/*' didn't match any documents
> > /home/jpodivin/repos/ci-framework/docs/source/index.rst:109: WARNING: toctree glob pattern 'roles/*' didn't match any documents
> > 
> > You can work around it by building the standard version first, and using the `sphinx-autobuild` just to serve it. But I'm not sure if the changes are going to propagate that way. 
> > ```
> 
> Thanks @jpodivin , I have added a new docs make target to build the auto generated content. I then pass that to `sphinx-autobuild` as a `--pre-build` command. I also added the source plugins directory as one to watch for changes and excluded the generated content from the watch as it causes a loop.
> 
> Please test and let me know if that helps the issues you discovered!

Thanks. I've verified that the documentation includes all parts of the CIFMW and that it's possible to edit it live. Great work.

2024-07-03 12:01 UTC, cjeanner approved these changes
/approve

2024-07-03 12:12 UTC, merged