Update cifmw-molecule-rhol_crc zuul job to CRC 2.39 - OCP 4.16
openstack-k8s-operators/ci-framework pull request #2102
Opened 2024-07-16 13:40 UTC by lewisdenny

Jira: https://issues.redhat.com/browse/OSPRH-8665
Jira: https://issues.redhat.com/browse/OSPCIX-376

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [ ] Appropriate documentation exists and/or is up-to-date:
  - [ ] README in the role
  - [ ] Content of the docs/source is reflecting the changes

2024-07-17 15:42 UTC, pablintino commented
recheck

2024-07-17 15:44 UTC, pablintino commented
recheck

2024-07-17 16:49 UTC, pablintino commented
recheck

2024-07-18 18:48 UTC, cjeanner commented
recheck

2024-07-19 05:17 UTC, lewisdenny commented
recheck

2024-07-19 06:55 UTC, cjeanner commented
recheck

2024-07-19 07:36 UTC, cjeanner requested changes

2024-07-19 07:36 UTC, cjeanner commented on roles/rhol_crc/tasks/cleanup.yml
I'd challenge the need there.

But there's indeed a need to edit the role: bumping the version in defaults/main.yml is mandatory, else the current way of doing things in the role will make it fetch the old CRC - and crash because no real pull-secret available.

2024-07-19 09:13 UTC, cjeanner commented on roles/rhol_crc/tasks/cleanup.yml
To be precise:
- removing that directory is a bad idea, since it means we have to re-download the bundle (~4G, maybe more, sometimes less)
- there's a better way to clean things up (I'm working on it) while keeping the cache
- in any cases, such a destructive thing should get the `never, deepscrub` tags, so that we hit it only when running a `--tags deepscrub`

We can of course discuss that precise change here, but I'm reworking the role, and that file is being changed to implement a better way to clean (calling delete -f + cleanup to ensure everything's removed but cached bundle)

2024-07-22 10:42 UTC, lewisdenny commented
Closing in favor of https://github.com/openstack-k8s-operators/ci-framework/pull/2123

2024-07-22 10:42 UTC, closed without merging