Rework a bit rhol_crc
openstack-k8s-operators/ci-framework pull request #2123
Opened 2024-07-19 11:53 UTC by cjeanner

There were multiple issues in the role:
- no version check, meaning it would consume whatever version it finds
  on the disk instead of ensuring it's consuming the target version
- lack of molecule tests for some specific and sensitive parts

This change also moves the "crc" binary to a more conventional location
(~/bin) to allow an easier discovery, and avoiding potential conflicts.

It also removes some wrong/useless parameters that could lead to weird
situations regarding rights, users and so on.

This PR also bumps the CRC version in both role and molecule (this
creates a conflict with another PR, #2102).

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role

2024-07-22 07:12 UTC, cjeanner commented
recheck

2024-07-22 14:13 UTC, cjeanner commented
Fixes for pre-commit are in #2134

2024-07-23 09:27 UTC, cjeanner commented on zuul.d/edpm.yaml
> +      cifmw_rhol_crc_binary_folder: "/usr/local/bin"
this is needed in order to ensure we're using the pre-installed CRC. Until now, it was fetching its own one, meaning we could have some weird situations.

2024-07-23 09:28 UTC, cjeanner commented on ci/config/molecule.yaml
> -    nodeset: centos-9-crc-2-36-0-xxl #TODO(Lewis): Bump to 2-39 once OSPCIX-376 is resolved
@lewisdenny so yep, it's done in here - up to you if you want me to split.

2024-07-23 09:28 UTC, cjeanner commented on roles/rhol_crc/defaults/main.yml
> -cifmw_rhol_crc_installyamls: "{{ cifmw_installyamls_repos | default('../..') }}"
not used - removed.

2024-07-24 05:10 UTC, lewisdenny requested changes
Thank you Cédric, big improvement! Have left some comments.

2024-07-24 05:10 UTC, lewisdenny commented on roles/rhol_crc/tasks/configuration.yml
> +        selectattr('key', 'match', 'cifmw_rhol_crc_config_patch_.*') |
I like this but I don't see where `cifmw_rhol_crc_config_patch_*` is documented.

2024-07-24 05:10 UTC, lewisdenny commented on roles/rhol_crc/README.md
>  * `cifmw_rhol_crc_version`: (String) RHOL/CRC binary version we want to use, set to `latest` to deploy latest CRC release. Default: `2.36.0`.
2.39.0

2024-07-24 05:10 UTC, lewisdenny commented on roles/rhol_crc/tasks/configuration.yml
> +        selectattr('key', 'match', 'cifmw_rhol_crc_config_patch_.*') |
Ah I see, there is a typo!

2024-07-24 05:10 UTC, lewisdenny commented on roles/rhol_crc/README.md
> +* `cifmw_rhol_crc_config`: (Dict) This structure is merged with the `cifmw_rhol_crc_config_defaults` dictionary. We can add extra properties or override the existing one using this parameter. We can
cifmw_rhol_crc_config_path_ should be cifmw_rhol_crc_config_patch_

2024-07-24 05:11 UTC, lewisdenny commented on roles/rhol_crc/tasks/configuration.yml
> +        selectattr('key', 'match', 'cifmw_rhol_crc_config_patch_.*') |
Ignore this one :)

2024-07-24 05:48 UTC, cjeanner commented
Comment addressed.

2024-07-24 06:05 UTC, lewisdenny approved these changes
/approve

2024-07-24 11:30 UTC, cjeanner commented
/hold

Some more testing via DS TP is requested.

2024-07-24 13:47 UTC, pablintino commented
/lgtm

2024-07-24 14:02 UTC, merged