[openshift_setup] Metal3 watch all NSs
openstack-k8s-operators/ci-framework pull request #2130
Opened 2024-07-22 07:47 UTC by pablintino

Under some circumstances, like when deploying BMH resources and its associated secrets in different namespaces, it may be necessary to allow Metal3's BMO access those resources out of its NS.

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

2024-07-22 11:21 UTC, cjeanner commented on roles/openshift_setup/tasks/main.yml
> +  when: not cifmw_openshift_setup_dry_run
with a "when", please move to `include_tasks` to improve speed:
https://ci-framework.readthedocs.io/en/latest/development/01_guidelines.html#include-vs-import (check the "rule of thumb")

2024-07-22 11:30 UTC, cjeanner commented on roles/openshift_setup/tasks/main.yml
> +  when: not cifmw_openshift_setup_dry_run
(note to self: I have to update the doc to effectively cover the `when` usage + include_*)

2024-07-22 11:36 UTC, cescgina commented
/lgtm

2024-07-22 12:06 UTC, raukadah commented
recheck

2024-07-22 14:14 UTC, rdiazcam commented
I tested this PR in my trunk job and it works (BHM is provisioned)

2024-07-23 02:54 UTC, lewisdenny commented
recheck

2024-07-23 03:05 UTC, lewisdenny requested changes
Thank you for the nice patch Pablo.

The bool vs boolean in our README files is interesting but you picked right :)  

My only concern is the extra refactoring that is not mentioned in the commit message or PR. 

I would like it if you moved this to it's own PR.

2024-07-23 03:05 UTC, lewisdenny commented on roles/openshift_setup/tasks/metal3_config.yml
> +      changed_when: "'no change' not in _cifmw_openshift_setup_provisioning_ns_patch_out.stdout"
Nice!

2024-07-23 10:07 UTC, pablintino commented
> Thank you for the nice patch Pablo.
> 
> The bool vs boolean in our README files is interesting but you picked right :)
> 
> My only concern is the extra refactoring that is not mentioned in the commit message or PR.
> 
> I would like it if you moved this to it's own PR.

Fixed.

2024-07-23 10:14 UTC, rebtoor approved these changes
/lgtm

2024-07-23 10:44 UTC, lewisdenny approved these changes
/approve

Thank you Pablo!

2024-07-23 13:36 UTC, merged