[pre-commit] Remove `bashate` hook
openstack-k8s-operators/ci-framework pull request #2265
Opened 2024-08-27 09:14 UTC by rebtoor

Since we're now using `shellcheck` to lint and validate shell scripts, we can remove `bashate` which contains only a subsets of checks implemented by shellcheck.

2024-08-27 09:56 UTC, lewisdenny requested changes

2024-08-27 09:56 UTC, lewisdenny commented on .pre-commit-config.yaml
>          # entry: bash -c "shellcheck "$@" || true" --
Could you also please remove this line.

2024-08-27 20:48 UTC, rebtoor commented on .pre-commit-config.yaml
>          # entry: bash -c "shellcheck "$@" || true" --
done!

2024-08-27 21:01 UTC, lewisdenny approved these changes
/approve

2024-08-28 04:52 UTC, raukadah commented
/lgtm

2024-08-28 04:57 UTC, merged