[WIP] Add nova multiplecells nodeset templates
openstack-k8s-operators/ci-framework pull request #2423
Opened 2024-10-03 16:59 UTC by jamepark4

2024-12-10 05:26 UTC, lewisdenny requested changes
lgtm, to get the docs ci job to pass you need to rebase to catch: https://github.com/openstack-k8s-operators/ci-framework/pull/2526

2024-12-10 16:28 UTC, jamepark4 commented on roles/ci_gen_kustomize_values/templates/nova-three-cells/edpm-nodeset2-values/values.yaml.j2
> +{% set nodset_two_instances = instances_names[inst_stop_idx:]                          %}
ack thankyou

2024-12-10 16:28 UTC, jamepark4 commented on roles/ci_gen_kustomize_values/templates/nova-three-cells/edpm-nodeset-values/values.yaml.j2
> +{% set nodset_one_instances = instances_names[:inst_stop_idx]                          %}
ack thank you

2024-12-10 23:13 UTC, hjensas reviewed
/lgtm

2024-12-11 00:31 UTC, lewisdenny approved these changes
/approve

2024-12-11 00:35 UTC, merged