DNM Check binding dnsmasq listen-address to 0.0.0.0
openstack-k8s-operators/ci-framework pull request #2454
Opened 2024-10-14 14:40 UTC by danpawlik

There is an issue, that the DNS requests are redirected to the cloud provider to resolve domain: api-int.crc.testing. Normally it is right that it want to resolve, but the dnsmasq should take the query and reply, however this is not the case.
Let's set the dnsmasq listen-address to be accessible to all addresses on that host.

2024-10-14 16:31 UTC, arxcruz commented
/ok-to-test

2024-10-15 12:05 UTC, danpawlik commented
recheck

2024-10-15 12:16 UTC, lewisdenny requested changes

2024-10-15 12:16 UTC, lewisdenny commented on roles/libvirt_manager/tasks/create_networks.yml
> +    cifmw_dnsmasq_network_listen_addresses:
Please drop this file from this PR

2024-10-15 12:16 UTC, lewisdenny commented on roles/ci_network/templates/local_domain.conf.j2
> +listen-address=0.0.0.0
Please drop this file from this PR

2024-10-15 12:16 UTC, lewisdenny commented on roles/ci_network/tasks/apply-dnsmasq.yml
> +        - "0.0.0.0"
Please drop this file from this PR

2024-10-15 12:16 UTC, lewisdenny commented on ci/playbooks/multinode-customizations.yml
> +                insertbefore: '^expand-hosts'
Is there a reason it needs to be before expand-hosts? if not, please just add it to EOF like line 95
```suggestion
                insertafter: "EOF"
```

2024-10-15 12:16 UTC, lewisdenny commented on ci/playbooks/multinode-customizations.yml
> +            - name: Print current config
Please remove this after your testing.

2024-10-15 13:14 UTC, danpawlik commented on ci/playbooks/multinode-customizations.yml
> +            - name: Print current config
of course ;)

2024-10-16 00:09 UTC, lewisdenny commented
recheck
infra issues: `Error: initializing source docker://quay.io/podified-antelope-centos9/openstack-iscsid:current-podified: pinging container registry quay.io: Get \\\"https://quay.io/v2/\\\": dial tcp: lookup quay.io:`

2024-10-16 08:03 UTC, danpawlik commented
Probably that change will require additional task that was proposed https://review.rdoproject.org/r/c/config/+/55035/4/roles/prepare-crc-extracted/tasks/dnsmasq-nm.yaml#80

which contains:
```
        - name: Set the bind interfaces
          become: true
          ansible.builtin.lineinfile:
            path: /etc/dnsmasq.d/crc-dnsmasq.conf
            line: "interface={{ item }}"
          loop: "{{ ansible_facts['interfaces'] }}"
          when: "{{ item.startswith('enp') }} or {{ item.startswith('eth') }}"
```
It is just a PoC.

2024-11-09 02:33 UTC, closed without merging