Reduce the days to stale a PR to 22
openstack-k8s-operators/ci-framework pull request #2460
Opened 2024-10-16 07:36 UTC by pablintino

2024-10-16 08:23 UTC, frenzyfriday commented
Sorry, 22 or 15?

2024-10-16 08:23 UTC, frenzyfriday commented
> Sorry, 22 or 15?

ah ok, I was being dumb 🤦🏽‍♀️

2024-10-16 08:23 UTC, frenzyfriday commented
/lgtm

2024-10-16 09:03 UTC, lewisdenny requested changes

2024-10-16 09:03 UTC, lewisdenny commented on .github/workflows/stale-pr.yml
>            start-date: '2024-04-25T00:00:00Z'
We should remove the start date now as well, this was added as a grace period when the stale bot was added but no longer needed.

2024-10-16 16:16 UTC, pablintino commented
recheck

2024-10-17 01:57 UTC, lewisdenny approved these changes
/approve

2024-10-20 20:30 UTC, frenzyfriday commented
/lgtm

2024-10-20 20:41 UTC, merged