Don't rely on all-group.yaml for adoption osp role
openstack-k8s-operators/ci-framework pull request #2461
Opened 2024-10-16 08:24 UTC by cescgina

Do not rely on reading the all-group.yaml file to parse all the vms
groups. Usually this would be correct, but since  we deploy ocp
separately from the osp vms, if the ocp playbooks runs afterwards it
rewrites the all-group file, leaving out the osp groups. This is becuase
in [1] we have to make the ocp deployment unaware of the rest of vms, to
avoid issues with config-drive.

[1] https://github.com/openstack-k8s-operators/ci-framework/pull/2445

2024-10-16 16:17 UTC, pablintino requested changes

2024-10-17 06:59 UTC, cescgina commented on deploy-osp-adoption.yml
> +        paths: "{{ ansible_user_dir }}/ci-framework-data/reproducer-inventory/"
good point, added the pattern, thanks

2024-10-17 08:01 UTC, pablintino approved these changes

2024-10-17 08:02 UTC, pablintino commented
/approve

2024-10-17 23:48 UTC, lewisdenny approved these changes
/lgtm

2024-10-17 23:52 UTC, merged