[hci_prepare] Ensure generated resources are applied in the proper NS
openstack-k8s-operators/ci-framework pull request #2464
Opened 2024-10-17 12:45 UTC by pablintino

The namespace field in the generated CRs is wronly placed. That, and the fact we call apply without specifying the namespace may lead to the resource to be applied to the wrong namespace.

2024-10-17 23:44 UTC, lewisdenny requested changes

2024-10-17 23:44 UTC, lewisdenny commented on roles/hci_prepare/tasks/common.yml
> +    __cifmw_hci_prepare_namespace: >-
```suggestion
    _cifmw_hci_prepare_namespace: >-
```

You have your brain in python mode :P

2024-10-18 07:37 UTC, pablintino commented on roles/hci_prepare/tasks/common.yml
> +    __cifmw_hci_prepare_namespace: >-
Fixed.

2024-10-18 07:51 UTC, lewisdenny approved these changes
/approve

2024-10-22 11:00 UTC, frenzyfriday commented
Do we need an additional var _cifmw_hci_prepare_namespace defined on the job defs now?

2024-10-22 11:17 UTC, lewisdenny commented
> Do we need an additional var _cifmw_hci_prepare_namespace defined on the job defs now?

Good question, no, this patch doesn't change the default behavior, it just allows cifmw_install_yamls_defaults to not be needed, when not provided we now have a default :)

If you want to override, which we don't by default, then you could set cifmw_hci_prepare_namespace in the job def but it's not needed.

2024-10-22 11:52 UTC, frenzyfriday commented
> > Do we need an additional var _cifmw_hci_prepare_namespace defined on the job defs now?
> 
> Good question, no, this patch doesn't change the default behavior, it just allows cifmw_install_yamls_defaults to not be needed, when not provided we now have a default :)
> 
> If you want to override, which we don't by default, then you could set cifmw_hci_prepare_namespace in the job def but it's not needed.

Ah, right right. This patch is setting the value for the _cifmw_hci_prepare_namespace, I missed that. Thanks!

2024-10-22 12:26 UTC, merged