[os_net_setup] Add --availability-zone-hint to network creation
openstack-k8s-operators/ci-framework pull request #2497
Opened 2024-10-29 12:27 UTC by eduolivares

This PR adds the option to configure external networks for certain AZs. In order to do this, the list `availability_zone_hints` should be configured as port of `cifmw_os_net_setup_config`.

2024-10-30 13:30 UTC, pablintino commented
/approve

2024-10-30 18:06 UTC, evallesp commented
(non-blocking) suggestion: I see some vars used in the template that are missing of some context and format.
Unsure what's the format of availability_zone_hints but I might have a lot of missing context.

WDYT about adding that to the default file: https://github.com/openstack-k8s-operators/ci-framework/blob/main/roles/os_net_setup/defaults/main.yml to see an example?

I'm thinking if it might make sense to rework eventually in the README file to briefly explain each of the possibilities of:  cifmw_os_net_setup_config

Apart of this: lgtm

2024-10-30 23:34 UTC, lewisdenny requested changes
I agree with @evallesp 

Please add availability_zone_hints to the role defaults, others are missing but they can be added in a follow up if we get time to refactor this role.

2024-10-31 14:15 UTC, eduolivares commented
recheck

2024-10-31 17:45 UTC, pablintino commented
recheck

2024-10-31 23:16 UTC, lewisdenny approved these changes
/lgtm

Thanks @eduolivares ++

2024-10-31 23:35 UTC, merged