Consider that the zuul executor may be an IP
openstack-k8s-operators/ci-framework pull request #2607
Opened 2024-12-16 15:21 UTC by pablintino

2024-12-17 22:31 UTC, hjensas requested changes

2024-12-17 22:31 UTC, hjensas commented on ci/playbooks/multinode-autohold.yml
> +                (zuul.executor.hostname | split('.'))[1:] | join('.'))
I think the last parantheses must be removed?

```
AnsibleError: template error while templating string: unexpected ')'. String: {{ zuul.executor.hostname if (zuul.executor.hostname is ansible.utils.ip) else (zuul.executor.hostname | split('.'))[1:] | join('.')) }}. unexpected ')'
```

2024-12-19 03:15 UTC, lewisdenny approved these changes
/approve

2024-12-19 12:13 UTC, hjensas approved these changes

2024-12-19 12:14 UTC, hjensas commented
/lgtm

2024-12-19 13:22 UTC, merged