Add possibility to run HorizonTest in debug mode
openstack-k8s-operators/ci-framework pull request #2627
Opened 2024-12-30 11:29 UTC by ashu-011

This patch adds support in the test-operator role to run HorizonTest tests in the debug mode (same as already is there for Tempest).

2024-12-30 14:09 UTC, ashu-011 commented
recheck

2024-12-30 18:57 UTC, ashu-011 commented
recheck

2025-01-02 07:43 UTC, ashu-011 commented
recheck

2025-01-05 23:57 UTC, lewisdenny requested changes

2025-01-05 23:57 UTC, lewisdenny commented on roles/test_operator/README.md
> +* `cifmw_test_operator_horizontest_debug`: (Bool) Run HorizonTest in debug mode, it keeps the operator pod sleeping infinity (it must only set to `true`only for debugging purposes). Default value: `f
```suggestion
* `cifmw_test_operator_horizontest_debug`: (Bool) Run HorizonTest in debug mode, it keeps the operator pod sleeping infinatly (it must only set to `true` only for debugging purposes). Default value: `false`
```

2025-01-10 14:42 UTC, frenzyfriday approved these changes
/lgtm

2025-01-10 14:43 UTC, frenzyfriday commented
recheck

the failure is not related to this patch

2025-01-10 14:57 UTC, pablintino commented on roles/test_operator/defaults/main.yml
> +    debug: "{{ cifmw_test_operator_horizontest_debug }}"
Why are we not continuing with the convention followed in the rest of the vars that makes variables stage scoped?
`debug: "{{ stage_vars_dict.cifmw_test_operator_horizontest_debug }}"`

2025-01-13 10:20 UTC, lpiwowar commented on roles/test_operator/defaults/main.yml
> +    debug: "{{ cifmw_test_operator_horizontest_debug }}"
+1 @pablintino . We should keep this consistent with the other parameters as well. 

@ashu-011 the reason why this update is needed is this PR -> https://github.com/openstack-k8s-operators/ci-framework/pull/2374

2025-01-13 14:54 UTC, ashu-011 commented on roles/test_operator/defaults/main.yml
> +    debug: "{{ cifmw_test_operator_horizontest_debug }}"
thanks guyz @pablintino and @lpiwowar for pointing it out , I have fixed it.

2025-01-13 15:10 UTC, pablintino commented
/approve

2025-01-13 15:12 UTC, frenzyfriday commented
/lgtm

2025-01-13 17:10 UTC, merged