Support post-config tweaks for CRC
openstack-k8s-operators/ci-framework pull request #309
Opened 2023-06-15 12:53 UTC by bogdando

Provide a customizable list of the post-config CRC commands. By default, it replicates the list of tweaks applied in OCP Prow CI: https://github.com/openshift/release/pull/34536

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

2023-06-15 12:55 UTC, pablintino commented
Seems like something that can be done with a hook?

2023-06-20 20:08 UTC, cjeanner requested changes
Couple of notes.

I'm OK with those configuration being part of the role. Hook wouldn't make sense here imho, even the `post_infra` one. Adding a new parameter is OK - passing down some defaults via a "static" var (compared to the "default") is also OK.

Reading the passed default config, I'm wondering if they wouldn't help alleviating the resource shortage we're hitting every now and then... ?

2023-06-20 20:08 UTC, cjeanner commented on ci_framework/roles/rhol_crc/tasks/main.yml
there's apparently a trailing whitespace at the end of one of the new lines you added.

2023-06-26 07:57 UTC, pablintino commented
Closed as replaced by https://github.com/openstack-k8s-operators/ci-framework/pull/327

2023-06-26 07:57 UTC, closed without merging