Use set_openstack_containers role to patch baremetal operator
openstack-k8s-operators/ci-framework pull request #372
Opened 2023-07-11 09:37 UTC by raukadah

set_openstack_containers role takes care of updating the env vars for any operator.

This pr uses the set_openstack_containers role to update the baremetal operator csv with the correct image.

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running

2023-07-12 01:28 UTC, raukadah commented
recheck

2023-07-12 05:46 UTC, raukadah commented
recheck

2023-07-13 08:45 UTC, cjeanner commented
/approve

Seems lovely - and working, according to a parallel test here: https://github.com/openstack-k8s-operators/edpm-image-builder/pull/11#issuecomment-1633820238

2023-07-13 09:20 UTC, Sandeepyadav93 commented on ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
> +      ansible.builtin.set_fact:
We need to override the image in periodic jobs as well, so that's why we originally kept the defaults and only update when the image is != default.

2023-07-13 14:45 UTC, Sandeepyadav93 requested changes

2023-07-13 14:45 UTC, Sandeepyadav93 commented on ci_framework/roles/edpm_deploy_baremetal/tasks/main.yml
> +- name: set facts for cifmw_edpm_deploy_baremetal_uefi_image_url
We don't have `cifmw_edpm_deploy_baremetal_uefi_image_url` var anymore

2023-07-13 14:45 UTC, Sandeepyadav93 commented on ci_framework/roles/set_openstack_containers/tasks/main.yml
> +- name: Print the operator pod name
We are literally printing operator_pod_name as string.


2023-07-13 09:14:14.686352 | controller | TASK [set_openstack_containers : Print the operator pod name msg=operator_pod_name] ***
2023-07-13 09:14:14.686358 | controller | Thursday 13 July 2023  09:14:14 -0400 (0:00:00.036)       0:18:23.420 *********
2023-07-13 09:14:14.725956 | controller | ok: [localhost] => {
2023-07-13 09:14:14.726022 | controller |     "msg": "operator_pod_name"
2023-07-13 09:14:14.726028 | controller | }

2023-07-13 14:52 UTC, Sandeepyadav93 commented on ci_framework/roles/set_openstack_containers/tasks/main.yml
> +- name: Print the operator pod name
done

2023-07-13 14:57 UTC, Sandeepyadav93 commented
/lgtm

2023-07-14 03:51 UTC, raukadah commented
recheck

2023-07-14 05:43 UTC, raukadah commented
recheck

2023-07-14 06:38 UTC, raukadah commented
recheck

2023-07-14 07:35 UTC, merged