QEHooks OSP-22851
openstack-k8s-operators/ci-framework pull request #54
Opened 2023-03-16 08:11 UTC by dsariel

- OSP-21172 Integrating the tempest stage
- Restructiure testing scenario folders

This PR has:
- [ ] Appropriate testing (molecule, python unit tests)
- [ ] Appropriate documentation (README in the role, main README is up-to-date)

2023-03-16 08:43 UTC, cjeanner requested changes
You should use the `ansible-galaxy` command described in the CONTRIBUTING.md file - you'll have the correct structure for the role(s) you're creating. Also, the playbooks should be located in ci_framework/hooks tree, just to show that they are hooks available for users.

2023-03-16 08:43 UTC, cjeanner commented on ci_framework/roles/tempest/ansible/ansibleee.yml
this should be in `ci_framework/roles/tempest/tasks/ansibleee.yml`

2023-03-16 08:43 UTC, cjeanner commented on ci_framework/roles/manual/ansible/main.yaml
what's the purpose of this empty file?

2023-03-16 08:43 UTC, cjeanner commented on ci_framework/roles/tempest/ansible/ansibleee.yml
> +  kubernetes.core.k8s:
this requirement has to be added in the /requirements.yml file, we already have most of the needs there

2023-03-16 08:43 UTC, cjeanner commented on ci_framework/roles/tobico/ansible/main.yaml
What's the purpose of this empty file ?

2023-03-16 11:43 UTC, arxcruz reviewed
I wonder where are you using the tempestconf to generate the tempest.conf file

2023-03-16 11:43 UTC, arxcruz commented on ci_framework/roles/tempest/ansible/create_clouds.yml
> +        clouds.yaml: "{{ clouds_yaml_file | to_nice_yaml }}"
No new line

2023-03-16 11:43 UTC, arxcruz commented on ci_framework/roles/tempest/ansible/templates/tempest_manifest.yaml.j2
> +  image: "quay.io/rhn_support_sbekkerm/ansibleee-tempest:latest"
is this fine? I mean, is this image fine to be used? This image is from a month ago, and I don't know if have the latest tempest.

2023-04-10 16:16 UTC, EliadCohen commented on ci_framework/roles/tobico/ansible/main.yaml
typo - tobiko

2023-04-13 14:19 UTC, cjeanner requested changes

2023-04-13 14:19 UTC, cjeanner commented on ci_framework/roles/tempest/defaults/main.yml
if there's no "defaults", we can remove the file and directory.

2023-04-13 14:19 UTC, cjeanner commented on ci_framework/roles/tempest/files/.gitkeep
if there's no file, we can remove this directory.

2023-04-13 14:19 UTC, cjeanner commented on ci_framework/roles/tempest/tasks/inventory
not used.

2023-04-13 14:19 UTC, cjeanner commented on ci_framework/roles/tempest/tasks/main.yml
this is a playbook, not a task file... This may lay in the hooks/playbooks/ directory then - though getting a real role, with parameters we may tweak, would be better. Tests (tempest, tobiko) are part of the CI - so we have to consider the best way to call them.

Tobiko may be a hook (as discussed), but tempest is worth an actual role, and proper integration in the "deploy-edpm.yml" main playbook.

2023-05-21 12:23 UTC, afazekas reviewed
This change was long in my review queue , Looks like I missed a lot at the first run tough weeks ago.

I wonder do we really need license at each file beginning, does it really needs to be the long version ?

Some question inline.

Also the commit message is really short, and title bit miss leading, at least for those does not knows the history behind it.

2023-05-21 12:23 UTC, afazekas commented on ci_framework/roles/tempest/tasks/prepare_cloud.yml
> +  - name: Create public subnet
Creating networks Does not really belongs to the test runner preparation.
It is something administrator should do regardless.

Probably it should  something like  os_post_config  role until there is a better idea.

2023-05-21 12:23 UTC, afazekas commented on ci_framework/roles/tempest/tasks/tempest.yml
> +          - ReadWriteOnce
Should be configurable, but as a default probably good.

2023-05-21 12:23 UTC, afazekas commented on ci_framework/roles/tempest/tasks/tempest.yml
> +                storage: 10G
configurable ?

2023-05-21 12:23 UTC, afazekas commented on ci_framework/roles/tempest/tasks/templates/tempest_manifest.yaml.j2
> +          configMap:
Open Stack Config Map:     openstack-config
  Open Stack Config Secret:  openstack-config-secret

Cannot we use simply use the above ones mounted ?

2023-06-15 06:07 UTC, cjeanner commented
Marking as `invalid`. There are other (cleaner) patches in the pipe. I propose to close this one - especially since it didn't change for a long time.

2023-07-04 08:49 UTC, cjeanner commented
Closing since it has been dangling for a long time - and most of the needs are implemented in dedicated PR already.

2023-07-04 08:49 UTC, closed without merging