Fail CI FMW execution when running as root
openstack-k8s-operators/ci-framework pull request #791
Opened 2023-11-08 19:19 UTC by dasm

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [ ] Appropriate documentation exists and/or is up-to-date:
  - [ ] README in the role
  - [ ] Content of the docs/source is reflecting the changes

2023-11-08 19:20 UTC, dasm commented
The documentation is already there: https://github.com/openstack-k8s-operators/ci-framework/blob/main/docs/source/quickstart/01_requirements.md?plain=1#L19

2023-11-08 19:30 UTC, dasm commented
/test pre-commit

2023-11-09 07:13 UTC, cjeanner requested changes

2023-11-09 07:13 UTC, cjeanner commented on ci_framework/playbooks/01-bootstrap.yml
> +    - name: Fail task execution when playbook is running as root.
I'd rather get a reusable role for those kind of validations. We also have to ensure the reproducer.yml (and subsequent clean plays) aren't called with root. Having a proper role, allowing to extend it in an easy way without having to edit 4 places, would be far easier to maintain.

2023-11-14 08:22 UTC, closed without merging