Add option to pass a URL for repo-setup config
openstack-k8s-operators/ci-framework pull request #85
Opened 2023-03-28 18:35 UTC by rlandy

plugins/module_utils/repo_setup/main.py#L246
offers an option to define the URL for the
mirror from which to install the openstack
packages. This review add the option to the
config call.

This PR has:
- [ ] Appropriate testing (molecule, python unit tests)
- [X ] Appropriate documentation (README in the role, main README is up-to-date)

2023-03-29 08:08 UTC, cjeanner requested changes
the `cifmw_` prefix is nasty, I know :).

2023-03-29 08:08 UTC, cjeanner commented on ci_framework/roles/repo_setup/README.md
> +* `cifwm_repo_setup_rdo_mirror`: Server from which to install RDO packages. Defaults to DLRN URI set above.
```suggestion
* `cifmw_repo_setup_rdo_mirror`: Server from which to install RDO packages. Defaults to DLRN URI set above.
```

2023-03-29 08:08 UTC, cjeanner commented on ci_framework/roles/repo_setup/defaults/main.yml
>  cifwm_repo_setup_dlrn_uri: "https://trunk.rdoproject.org/"
```suggestion
cifmw_repo_setup_dlrn_uri: "https://trunk.rdoproject.org/"
```

2023-03-29 08:08 UTC, cjeanner commented on ci_framework/roles/repo_setup/defaults/main.yml
> +cifwm_repo_setup_rdo_mirror: "{{ cifwm_repo_setup_dlrn_uri }}"
```suggestion
cifmw_repo_setup_rdo_mirror: "{{ cifmw_repo_setup_dlrn_uri }}"
```

2023-03-29 08:08 UTC, cjeanner commented on ci_framework/roles/repo_setup/README.md
>  * `cifwm_repo_setup_dlrn_uri`: DLRN base URI. Defaults to https://trunk.rdoproject.org/
```suggestion
* `cifmw_repo_setup_dlrn_uri`: DLRN base URI. Defaults to https://trunk.rdoproject.org/
```

It probably slipped unnoticed last time

2023-03-29 14:04 UTC, cjeanner commented
/lgtm

2023-03-29 14:07 UTC, merged

2023-03-30 06:30 UTC, marios reviewed
looks good

thanks for including a commit message but next time please include a URL when you refer to a file like that (I had to go looking for it)

2023-03-30 06:30 UTC, marios commented on ci_framework/roles/repo_setup/README.md
> +* `cifmw_repo_setup_rdo_mirror`: Server from which to install RDO packages. Defaults to DLRN URI.
Defaults to "{{ cifmw_repo_setup_dlrn_uri }}"