Molecule fix avoiding 'failed to create tmp dir' error
openstack-k8s-operators/ci-framework pull request #92
Opened 2023-03-31 06:46 UTC by dsariel

Molecule produces it's own ansible configuration file under:

/home/<user>/.cache/molecule/<role>/<scenario>/ansible.cfg

This fix is modifying the provisionner environment in molecule.yml
files in order to instruct molecule to generate correct per role/secnario
ansible.cfg.

See: https://stackoverflow.com/questions/74393035/molecule-test-seems-to-ignore-ansible-cfgs-remote-tmp-setting

This PR has:
- [ ] Appropriate testing (molecule, python unit tests)
- [ ] Appropriate documentation (README in the role, main README is up-to-date)

2023-03-31 06:53 UTC, cjeanner requested changes
Good idea - though that's the kind of change you want to push here:
https://github.com/openstack-k8s-operators/ci-framework/tree/main/.config/molecule

It will be inherited by all the jobs, automatically.

Note that Prow job has exported env var for that - and I didn't get that issue locally when running the container. But it doesn't hurt to get it.

2023-04-02 14:09 UTC, dsariel commented
> Good idea - though that's the kind of change you want to push here: https://github.com/openstack-k8s-operators/ci-framework/tree/main/.config/molecule
> 
> It will be inherited by all the jobs, automatically.
> 
> Note that Prow job has exported env var for that - and I didn't get that issue locally when running the container. But it doesn't hurt to get it.

Ack. Done.

2023-04-02 14:10 UTC, dsariel commented
/test all

2023-04-02 14:13 UTC, dsariel commented
/test all

2023-04-03 06:55 UTC, cjeanner requested changes

2023-04-03 06:55 UTC, cjeanner commented on .config/molecule/config_local.yml
> +  config_options:
it's already declared line 19 - please move your own config there.

2023-04-03 15:25 UTC, cjeanner approved these changes

2023-04-03 15:42 UTC, merged