TF role
openstack-k8s-operators/ci-framework pull request #976
Opened 2023-12-20 13:59 UTC by eshulman2

adding TF provisioning role

As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [ ] Appropriate documentation exists and/or is up-to-date:
  - [ ] README in the role
  - [ ] Content of the docs/source is reflecting the changes

2023-12-21 01:53 UTC, lewisdenny commented
/ok-to-test

@eshulman2 Please resolve conflicts

2023-12-21 13:36 UTC, rebtoor requested changes

2023-12-21 13:36 UTC, rebtoor commented on ci_framework/roles/terraform/tasks/terraform_environment/prepare.yaml
> +- name: Unarhive Terraform Binary
typo `Unarchive`

2023-12-28 03:13 UTC, SeanMooney commented
I would think twice before adding tereform to the tech stack we use. Adding another technology should not be done lightly. We already have an non trivial tech stack and tereform is nolnger available under a recognised open source license https://thenewstack.io/hashicorp-abandons-open-source-for-business-source-license/

It has already been forked as a result and the fork has been adopted by the Linux foundation
https://www.linuxfoundation.org/press/announcing-opentofu

Before proceeding with tereform support we should first answer why ansible cannot be used instead and then consider if https://opentofu.org/ would be more appropriate.

2024-01-01 08:09 UTC, dpinhas commented
This code is basically cloned and modified to match cifmw, but it exists in rhos-infra infrared project
https://github.com/rhos-infra/terraform
Can this implementation be re-evaluated? I rather have a role/hook that calls the existing role rather than having it multiple times in our maintained catalog repos.

2024-01-01 08:11 UTC, dpinhas requested changes
This code is basically cloned and modified to match cifmw, but it exists in rhos-infra infrared project
https://github.com/rhos-infra/terraform
Can this implementation be re-evaluated? I rather have a role/hook that calls the existing role rather than having it multiple times in our maintained catalog repos.

2024-01-17 08:53 UTC, rebtoor requested changes

2024-01-17 08:53 UTC, rebtoor commented on roles/tofu/tasks/prepare.yml
> +  ansible.builtin.yum:
let's use `ansible.builtin.dnf` instead

2024-01-17 08:53 UTC, rebtoor commented on roles/tofu/tasks/prepare.yml
> +  register: tofu_binary_path
I don't see any reference of `tofu_binary_path`, why we need to register it?

2024-01-17 08:53 UTC, rebtoor commented on roles/tofu/tasks/remote_prepare.yml
> +    state: directory
it's considered a best practice to define the file/directory permissions using `mode` attribute when you create a file/directory with ansible.

2024-01-17 08:55 UTC, rebtoor requested changes
There's an extra pre-commit error that could be fixed launching:

```
make role_molecule
``` 

from the root of the project.

Can i also ask you to squash commits in a single one? Thanks a lot!

2024-01-17 08:55 UTC, rebtoor commented on playbooks/run_tofu.yml
> +
if you remove this extra line it will fix the linting error.

2024-01-17 13:21 UTC, rebtoor commented on ci_framework/roles
this one isn't clear to me :sweat_smile:

2024-01-17 13:27 UTC, rebtoor requested changes
just few minor issues :)

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/README.md
> +* `tofu_backend_config_files`: List of files containing tofu back end configuration.
the prefix `cifmw_` is missing here

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/tasks/main.yml
> +    - name: Prepare Terrafrom Environment
Tofu?

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/tasks/main.yml
> +    - name: Execute  Tofu  Plan
i guess the extra spacing comes from a mass replace

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/tasks/main.yml
> +    - name: Notify Error In Execution  Tofu  Plan
same here (extra spacing)

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/tasks/plan.yml
> +  register: tofu_plan_execution
in case like this, where the variable is used for the scope of the role, consider use `_` as prefix:

e.g. `_tofu_plan_execution`

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/tasks/prepare.yml
> +  register: tofu_binary_path
can we use the `_` prefix for this variable?

2024-01-17 13:27 UTC, rebtoor commented on roles/tofu/molecule/files/main.tf
> +    name = "terraform-example"
tofu-example?

2024-01-17 14:08 UTC, eshulman2 commented on ci_framework/roles
what isn't clear?

2024-01-17 15:09 UTC, rebtoor reviewed
+2 for me, I'll wait for another pair of eyes to take a look at it :)

2024-01-17 15:35 UTC, rebtoor commented on ci_framework/roles
sorry, i lost this comment. We are you deleting this symbolic link?

2024-01-17 15:44 UTC, cjeanner commented
/approve

2024-01-17 15:56 UTC, pablintino requested changes

2024-01-17 15:56 UTC, pablintino commented on ci_framework/roles
This file shouldn't be removed here, in this PR, it requires some analysis, cause it's used (or it was used) in other repos.
I have created a dedicated task for it. https://issues.redhat.com/browse/OSPRH-3739

2024-01-17 16:04 UTC, rebtoor approved these changes

2024-01-17 16:29 UTC, pablintino commented
/lgtm

2024-01-17 17:55 UTC, merged