Enable better logging for rhol_crc
openstack-k8s-operators/ci-framework pull request #997
Opened 2024-01-04 11:54 UTC by cjeanner

Until now, we were missing all of the setup and startup logs for the
CRC.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

2024-01-05 03:01 UTC, lewisdenny requested changes
Hi @cjeanner, thank you. Small comment left, log file [1] looked a little small, I believe some logs are being overridden.

[1] https://logserver.rdoproject.org/97/997/ebcd2436e3392666fb26ba098d970d1c808bad94/github-check/cifmw-molecule-rhol_crc/19d930a/ci-framework-data/logs/crc-config.log

2024-01-05 03:01 UTC, lewisdenny commented on roles/rhol_crc/tasks/main.yml
> +              tee {{ cifmw_rhol_crc_basedir }}/logs/crc-start.log
ditto

2024-01-05 08:23 UTC, marios requested changes
nit as commented by Lewis

2024-01-05 08:23 UTC, marios commented on roles/rhol_crc/tasks/main.yml
> +              tee {{ cifmw_rhol_crc_basedir }}/logs/crc-setup.log
```
       -a, --append
              append to the given FILEs, do not overwrite
 ```

2024-01-05 12:43 UTC, cjeanner commented on roles/rhol_crc/tasks/main.yml
> +              tee {{ cifmw_rhol_crc_basedir }}/logs/crc-setup.log
I don't think we need to `-a` here since we're running it once.

2024-01-05 12:44 UTC, cjeanner commented on roles/rhol_crc/tasks/configuration.yml
> +          tee -a {{ cifmw_rhol_crc_basedir }}/logs/crc-config.log
here the `-a` makes sense since we're looping on a list

2024-01-05 14:10 UTC, cjeanner commented on roles/rhol_crc/tasks/configuration.yml
> +          tee -a {{ cifmw_rhol_crc_basedir }}/logs/crc-config.log
as a matter of fact, this is the exact log @lewisdenny linked while talking about "small log" :). We don't configure many things in there anyway, but we do `append`.

2024-01-07 23:54 UTC, lewisdenny commented on roles/rhol_crc/tasks/main.yml
> +              tee {{ cifmw_rhol_crc_basedir }}/logs/crc-setup.log
Thanks Cédric, I misread  `crc-setup.log` and `crc-start.log` as the same file 😞

2024-01-07 23:54 UTC, lewisdenny approved these changes

2024-01-08 07:57 UTC, marios approved these changes
lgtm

2024-01-08 07:57 UTC, marios commented on roles/rhol_crc/tasks/main.yml
> +              tee {{ cifmw_rhol_crc_basedir }}/logs/crc-setup.log
ack. i mean, the -a would not hurt in this case but indeed there is no where else writing to this file as far as i could grep (crc setup is something we do once)

2024-01-08 08:38 UTC, pablintino commented
/approve

2024-01-08 08:54 UTC, merged